[package]
name = "armdecode"
version = "0.1.0"
authors = ["meta <hosaka-corp@users.noreply.github.com>"]
edition = "2018"

[dependencies]
armbf = { path = "bf/armbf" }
armbf_prim = { path = "bf/armbf_prim" }

