[package]
name = "armbf_derive"
version = "0.1.0"
authors = ["meta <hosaka-corp@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
armbf_prim = { path = "../armbf_prim" }
